# Generated by Django 5.1.5 on 2025-01-29 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoriesModel',
            new_name='Categories',
        ),
    ]
