# Generated by Django 5.1.5 on 2025-01-30 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_rename_categoriesmodel_categories'),
        ('plants', '0006_alter_plants_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plants',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='categories.categories'),
        ),
    ]
