# Generated by Django 5.1.5 on 2025-01-31 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0007_alter_plants_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plants',
            name='image',
        ),
        migrations.AddField(
            model_name='plants',
            name='img',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
