# Generated by Django 5.1.5 on 2025-02-08 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0014_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='image',
            new_name='img',
        ),
    ]
